### ISSUE TITLE
Figure out an emoji for Spikes

### ISSUE THREAD

**Issue by stefanfoulis** [oschrenk/scrumoji#2]
Hello @oschrenk :sunglasses:!

At first I thought about using an emoji that plays on spikes being pointy, like 🤺⚔️🗡🔪🧷. On the other hand, a Spike is about investigating and clarifying something... so maybe better a detective 🕵️‍♀️?

What do you think?

**Comment by oschrenk** [comment]
Have to think about it.

I think I prefer an object over a person emoji - maybe 💉?

**Comment by stefanfoulis** [comment]
Right, I agree. Use people emojis for roles that actually are people (like the existing ones for product owner, scrum master, ...)
🤔

**Comment by oschrenk** [comment]
Another thought. Use

**Comment by oschrenk** [comment]
Another thought.

Use 🔎for Spike, and use 🍷 ,✨, or 💅 for Refinement

**Comment by stefanfoulis** [comment]
Yes, I like the idea of 🔎 for Spike and 💅 for Refinement.

**Comment by oschrenk** [comment]
+1 

Can you do a pull request? 

(will merge it next week then.

**Comment by oschrenk** [comment]
It's actually already live for a few days and it is  💅.
