### ISSUE TITLE
Update: Business Value = trophy

### ISSUE THREAD

**Issue by paulera** [oschrenk/scrumoji#21]
- Emoji: 🏆 
- Code: `:trophy:`
- Description: Business Value

Business value is not always money, and it doesn't mean money flying away either. Every time business value is achieved and delivered, it is a win for the team (or should be seen as).

**Comment by oschrenk** [comment]
Thank you for your work and the clean separation of issues. I will get to all of them one way or another in the next couple of days. 

Without having them all reviewed yet, I definitely agree with this change.
