### ISSUE TITLE
The tweet button still sends the original moto from gitmoji

### ISSUE THREAD

**Issue by paulera** [oschrenk/scrumoji#25]
The `Tweet` button on the homepage tweets the original moto from Gitmoji
![image](https://user-images.githubusercontent.com/2051955/89006903-fbbe3580-d307-11ea-8718-2102fbe860f3.png)

I suppose the tweet should be _"scrumoji – An #emoji guide for your **Agile communication** by @oschrenk 😍😜 https://scrumoji.org"_

**Comment by oschrenk** [comment]
Thanks! I am really grateful for your contributions!

**Comment by paulera** [comment]
Happy to help! 🙏
