### ISSUE TITLE
Brainstorm Daily standup / check in emoji

### ISSUE THREAD

**Issue by scheib** [oschrenk/scrumoji#27]
Hello @oschrenk :sunglasses:!

Suggesting a brainstorm of emoji to use for daily standups.

Some initial thoughts for [Last day's work], [today's], and [blockers]:

- ⏪, ▶️, ⏸️ 
- 👈, 🌞, 🚦
- ?, 🟢, 🛑

**Comment by oschrenk** [comment]
🛑 for Blocker/impediment immediately resonates with me. 

Could elaborate on the use of the other emojis?

**Comment by scheib** [comment]
One example use:
⏪ yesterday: Finished first patch for Feature
▶️ today: Get patch reviewed, start tests for OtherThing
🚦 blockers: none

or alternates:
👈 yesterday: Finished first patch for Feature
🌞 today: Get patch reviewed, start tests for OtherThing
🛑 blockers: none

I'm hoping to hear from others who've found ones they like.

**Comment by oschrenk** [comment]
I ended up with

⏪ yesterday: Finished first patch for Feature
▶️ today: Get patch reviewed, start tests for OtherThing
🛑 blockers: none

But I am having a hard time getting a colored "play" button into the actual code (I'm even hvaing troubles it just copy pasting it in this box)

My editors are swallowing the control characters for the emoji variation. I busted out a hex editor to get it in but I guess I am too tired this evening -  I can't seem to convince the tooling that it should be colorful and not black and white. Will try again some time later

**Comment by scheib** [comment]
Have tried a few different things with a team.  One change that stuck so far is using ✅ .

✅ done: Finished first patch for Feature
▶️ today: Get patch reviewed, start tests for OtherThing
🛑 blockers: none
