### ISSUE TITLE
Missing Emojis: UX, QA

### ISSUE THREAD

**Issue by oschrenk** [oschrenk/scrumoji#4]

**Comment by fedragon** [comment]
@oschrenk would you consider 📜 as an emoji for acceptance criteria?

**Comment by oschrenk** [comment]
Not at all! It's a good idea. Do you want to create a pull request? Should be as easy as editing a json file, see https://github.com/oschrenk/scrumoji/pull/1 . I'll take care of publishing it.

**Comment by fedragon** [comment]
Sure! See #5

**Comment by fedragon** [comment]
Since I'm here already... :)

What do you think about these?
UX designer: 👩‍🎨 
QA: 🕵️‍♀️ or 👩‍🔧

**Comment by oschrenk** [comment]
They are both good suggestions. I would like to have a better distinction between the process and the person

Maybe adding 4 emojis?

* UX 🎨 
* UX Desginer 👩‍🎨

* QA 🔧
* QA Engineer 👩‍🔧

???

**Comment by fedragon** [comment]
Looks good to me! Will create a PR

**Comment by oschrenk** [comment]
Thanks @fedragon ! I merged #5 and #6
